---
driver:
  name: vagrant
  customize:
    nictype1: "virtio"
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.21.4
  environments_path: '.chef/environments'
  data_bags_path: '.chef/data_bags'
  nodes_path: '.chef/nodes'
  roles_path: '.chef/roles'

platforms:
  - name: debian-8.4

suites:
  - name: default
    run_list:
      - recipe[git_dwk::kitchen]
    attributes:
