AllCops:
  Include:
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Thorfile'
    - '**/Guardfile'
  Exclude:
    - 'vendor/**/*'
    - 'foodcritic-rules/**/*'

ClassLength:
  Enabled: true
Documentation:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Enabled: true
SignalException:
  Enabled: true
TrailingCommaInLiteral:
  Enabled: true
TrailingCommaInArguments:
  Enabled: true
WordArray:
  Enabled: true
